### ISSUE TITLE
HTML Markup Errors

### ISSUE THREAD

**Issue by fuerbringer** [wirechan/iikoto#4]
The site seems to have malformed HTML-tags and markup errors.
### Examples

- [x] Stray `<footer>` tag after the `body` element. Occurence: global.
- [ ] Incorrect `hr` tag: `</hr>`. Should be `<hr>`. Occurence: /q/ board.

**Comment by chihiro** [comment]
fixed the footer: f4e72814f30f599051663e0d69f33605986cb4c8

**Comment by chihiro** [comment]
slim (templating engine) doesn't seem to have the capability to avoid closing `hr`. i looked for any documentation on `hr` and checked the github issues however there's no mention of it.
